# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- releases/*
- develop
- feature/*

jobs:

- job: 'TestLinux'
  pool:
    vmImage: 'Ubuntu 16.04'
  strategy:
    matrix:
      Python27-x64:
        python.version: '2.7'
        python.architecture: 'x64'
      Python35-x64:
        python.version: '3.5'
        python.architecture: 'x64'
      Python36-x64:
        python.version: '3.6'
        python.architecture: 'x64'
      Python37-x64:
        python.version: '3.7'
        python.architecture: 'x64'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'

  - script: sudo apt install cmake build-essential libglib2.0-dev bluez bluetooth python-dev python3-dev libbluetooth-dev libboost-python-dev libboost-thread-dev
    displayName: 'Install system dependencies'

  - script: python -m pip install --upgrade pip && pip install -r requirements.txt
    displayName: 'Install Python dependencies'

  - script: |
      pip install pytest pytest-cov mock
      pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov pymetawear --cov-report term-missing
    displayName: 'pytest'

  - task: PublishTestResults@2
    inputs:
      testResultsFiles: '**/test-results.xml'
      testRunTitle: 'Python $(python.version)'
    condition: succeededOrFailed()

- job: 'Publish'
  dependsOn: 'TestLinux'
  pool:
    vmImage: 'Ubuntu 16.04'

  strategy:
    matrix:
      Python27-x64:
        python.version: '2.7'
        python.architecture: 'x64'
      Python35-x64:
        python.version: '3.5'
        python.architecture: 'x64'
      Python36-x64:
        python.version: '3.6'
        python.architecture: 'x64'
      Python37-x64:
        python.version: '3.7'
        python.architecture: 'x64'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: '$(python.architecture)'

  - script: sudo apt install cmake build-essential libglib2.0-dev bluez bluetooth python-dev python3-dev libbluetooth-dev libboost-python-dev libboost-thread-dev
    displayName: 'Install system dependencies'

  - script: python -m pip install --upgrade pip && pip install -U setuptools wheel
    displayName: 'Install Python dependencies'

  - script: python setup.py sdist bdist_wheel
    displayName: 'Build sdist and bdist_wheel'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: dist'
    inputs:
      PathtoPublish: dist
      ArtifactName: 'dist-$(python.version)-$(python.architecture)'

